In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.,)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
t3 = torch.tensor([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11.,12]]
])
t3.dtype

torch.float32

In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 2, 3])


In [ ]:
print(torch.tensor([3.]).shape)
print(torch.tensor([3.]))

torch.Size([1])
tensor([3.])


In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(3.)
tensor(1.)


In [ ]:
x = torch.tensor(5)
x

tensor(5)

## Linear Regression

In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
  inputs = torch.from_numpy(inputs)
  targets = torch.from_numpy(targets)
  print(inputs.shape)
  print(targets.shape)

torch.Size([5, 3])
torch.Size([5, 2])


In [ ]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.2210,  0.4894,  0.0460],
        [-0.1479, -0.4249, -1.2163]], requires_grad=True)
tensor([ 0.5183, -0.0771], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
preds = model(inputs)
print(preds)
print(targets)
print((preds - targets) ** 2)

tensor([[  51.4171,  -91.6413],
        [  66.6379, -128.7679],
        [  87.9922, -140.4224],
        [  45.8025,  -78.4366],
        [  65.9682, -136.2101]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[2.1003e+01, 2.6128e+04],
        [2.0627e+02, 5.2793e+04],
        [9.6148e+02, 7.4760e+04],
        [5.6656e+02, 1.3326e+04],
        [1.3714e+03, 6.5132e+04]], grad_fn=<PowBackward0>)


In [ ]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff ** 2)/diff.numel()

In [ ]:
loss = mse(preds,targets)

In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.2210,  0.4894,  0.0460],
        [-0.1479, -0.4249, -1.2163]], requires_grad=True)
tensor([[  -893.3051,  -1651.5020,   -925.2454],
        [-17176.0957, -19430.4180, -11930.0166]])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
preds = model(inputs)
preds

tensor([[  51.4171,  -91.6413],
        [  66.6379, -128.7679],
        [  87.9922, -140.4224],
        [  45.8025,  -78.4366],
        [  65.9682, -136.2101]], grad_fn=<AddBackward0>)

In [ ]:
loss = mse(preds,targets)
print(loss)

tensor(23526.5508, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  -893.3051,  -1651.5020,   -925.2454],
        [-17176.0957, -19430.4180, -11930.0166]])
tensor([ -12.6364, -207.0957])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.2299,  0.5060,  0.0552],
        [ 0.0238, -0.2306, -1.0970]], requires_grad=True)
tensor([ 0.5185, -0.0750], requires_grad=True)


In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(16066.5059, grad_fn=<DivBackward0>)


In [ ]:
for i in range(10000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
  if (i+1)%1000 == 0:
    print(f"Loss: {loss} for i: {i+1}")

Loss: 0.5210826992988586 for i: 1000
Loss: 0.5210753679275513 for i: 2000
Loss: 0.5210692882537842 for i: 3000
Loss: 0.5210617780685425 for i: 4000
Loss: 0.5210579633712769 for i: 5000
Loss: 0.5210500359535217 for i: 6000
Loss: 0.5210436582565308 for i: 7000
Loss: 0.5210350751876831 for i: 8000
Loss: 0.5210351943969727 for i: 9000
Loss: 0.5210270881652832 for i: 10000


In [ ]:
print(w)
print(b)

tensor([[-0.4042,  0.8481,  0.6841],
        [-0.3017,  0.7944,  0.9109]], requires_grad=True)
tensor([ 0.5140, -0.0682], requires_grad=True)


In [ ]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 57.2511,  70.2976],
        [ 82.1530, 100.6773],
        [118.6791, 132.9604],
        [ 21.0705,  37.0166],
        [101.9343, 119.1361]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear Regression using Python builtin functions

In [1]:
import torch.nn as nn
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
from torch.utils.data import TensorDataset

In [4]:
train_ds = TensorDataset(inputs, targets)
print(train_ds[0:3][1])
train_ds[0:3]

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [5]:
from torch.utils.data import DataLoader

In [6]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
train_dl

In [7]:
for xb, yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 88., 134.,  59.],
        [ 87., 134.,  58.],
        [ 73.,  66.,  44.],
        [ 74.,  66.,  43.],
        [ 69.,  96.,  70.]])
tensor([[118., 132.],
        [119., 133.],
        [ 57.,  69.],
        [ 57.,  69.],
        [103., 119.]])
tensor([[103.,  43.,  36.],
        [ 68.,  97.,  70.],
        [ 87., 135.,  57.],
        [ 92.,  87.,  64.],
        [101.,  44.,  37.]])
tensor([[ 20.,  38.],
        [102., 120.],
        [118., 134.],
        [ 82., 100.],
        [ 21.,  38.]])
tensor([[ 91.,  88.,  64.],
        [ 68.,  96.,  71.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 91.,  87.,  65.]])
tensor([[ 81., 101.],
        [104., 118.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 80., 102.]])


In [8]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4249,  0.1359,  0.2976],
        [-0.0347,  0.1416,  0.0912]], requires_grad=True)
Parameter containing:
tensor([0.0079, 0.1942], requires_grad=True)


In [9]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4249,  0.1359,  0.2976],
         [-0.0347,  0.1416,  0.0912]], requires_grad=True),
 Parameter containing:
 tensor([0.0079, 0.1942], requires_grad=True)]

In [10]:
preds = model(inputs)
preds

tensor([[ -9.1083,  11.0724],
        [ -7.6527,  15.3377],
        [ -1.4880,  21.4445],
        [-26.4784,   6.1190],
        [  4.5686,  17.7819],
        [ -9.6691,  10.8961],
        [ -7.4910,  15.2873],
        [ -1.6153,  21.5010],
        [-25.9175,   6.2954],
        [  5.2912,  17.9079],
        [ -8.9465,  11.0220],
        [ -8.2136,  15.1614],
        [ -1.6498,  21.4949],
        [-27.2009,   5.9931],
        [  5.1294,  17.9583]], grad_fn=<AddmmBackward0>)

In [11]:
import torch.nn.functional as F

In [12]:
loss_fn = F.mse_loss

In [13]:
loss = loss_fn(model(inputs), targets)
loss

tensor(7288.5996, grad_fn=<MseLossBackward0>)

In [28]:
optim = torch.optim.SGD(model.parameters(), lr=1e-6)

In [31]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()

        if (epoch+1) % (num_epochs / 10) == 0:
            print(f"Epoch: {epoch+1}/{num_epochs}, Loss: {loss:.4f}")

In [32]:
fit(10000, model, loss_fn, optim, train_dl)

Epoch: 1000/10000, Loss: 3.3366
Epoch: 2000/10000, Loss: 2.3081
Epoch: 3000/10000, Loss: 1.0640
Epoch: 4000/10000, Loss: 1.7084
Epoch: 5000/10000, Loss: 2.0388
Epoch: 6000/10000, Loss: 1.1491
Epoch: 7000/10000, Loss: 1.4649
Epoch: 8000/10000, Loss: 1.1168
Epoch: 9000/10000, Loss: 1.1682
Epoch: 10000/10000, Loss: 0.9950


In [33]:
print(model(inputs))
print(targets)

tensor([[ 56.9547,  70.4390],
        [ 82.0173, 100.4159],
        [118.2226, 133.0009],
        [ 20.8272,  37.8061],
        [101.8309, 118.2962],
        [ 55.7078,  69.3570],
        [ 81.8714, 100.4920],
        [118.5155, 133.5901],
        [ 22.0741,  38.8881],
        [102.9319, 119.4544],
        [ 56.8088,  70.5151],
        [ 80.7704,  99.3338],
        [118.3685, 132.9248],
        [ 19.7262,  36.6480],
        [103.0778, 119.3783]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])
