# Numpy Implementation

In [4]:
import numpy as np
# Create a 2D Numpy array of size 1x3 with elements of your choice
arr1= np.arange(3).reshape(1,3)

# Create a Numpy array of length 50 with zeroes as its elements
arr2= np.zeros(50)

#Create a Numpy array of length 3x2 with elements of your choice
arr3= np.arange(6).reshape(3,2)

arr4= np.dot(arr1,arr3)

#Change 5th element of arr2 to a different number
arr2[4] = 1
#Your code here

if np.shape(arr4)==(1,2) and arr2[4]!=0:
  print("Passed")
else:
  print("Fail")

Passed


In [7]:
import numpy as np

#Task: Perform the dot product of I and 9I+1 using numpy, here I is referred to as an 3x3 Identity matrix.
a1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
a2 = 9 * a1 + 1
a3 = np.dot(a1,a2)
print(a3)

[[10  1  1]
 [ 1 10  1]
 [ 1  1 10]]


# Pandas Implementation

In [ ]:
import pandas as pd

## Create a DataFrame from a dictionary
data = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, 30, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}
#Your code here

#Display the first 2 rows of the data frame
#Your code here

#Print the age column
#Your code here

#Filter rows where age is greater than 26
#Your code here

#Add a new column 'Country' with the value 'India' for all rows
#Your code here

data1 = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, None, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}

df2= pd.DataFrame(data1)

# Fill missing values in the 'Age' column with the mean age
#Your code here

# Matplotlib Implementation

In [ ]:
import matplotlib.pyplot as plt
import #numpy module. Fill your code



xpoints=np.array([1,2,3,4])
ypoints=np.array([2,4,6,8])

#Plot these points without drawing a line
#Your code here

#Plotting with marker: Plot these points with a marker(Star marker)
#Your code here

#Using fmt format, add circular marker,red color and Dashed line
#Your code here

#Add xlabel,ylabel and title for the plot.
#Your code here

#Create a scatter plot for xpoints and ypoints
#Your code here

#Set color to the scatter plot. Blue,Green,Red and yellow color for each point respectively


SyntaxError: invalid syntax (<ipython-input-5-8ace55936b42>, line 2)

# Miscellaneous Modules Implementation

In [ ]:
import random
import numpy as np

#Set the seed of random to 20
#Your code here

arr1=np.array([1,24,31,45,73,81,94,25])

#Using the random module pick 4 different random numbers from arr1 and return their sum.
#Your code here